### ISSUE TITLE
After using the Partial Transfer Plugin on 5.3, you’re stuck on the section you have selected and crash when exiting.

### ISSUE THREAD

**Issue by WhatAUsernameIHave** [Deijin27/RanseiLink#24]

**Comment by Deijin27** [comment]
I have a fix for this, just need to finish implementing it.

It will not require changes to ranseilink, its an issue with the plugin not doing thing correctly, so I will just update the plugin.

It affects both partial transfer and changelist plugins, where they dispose of a service provider that they shouldnt.

And there is an extra issue with partialtransfer where it isnt reloading the services where is does a file copy since it was desinged back before the services cached their data.

**Comment by Deijin27** [comment]
Correction. Everything but text works. This will require a ranseilink update. Oversight in the text module means it's near impossible to update via plugins.

**Comment by WhatAUsernameIHave** [comment]
Issue persists in 5.4 Beta
![72BF131F-8B83-4733-A659-CD45CD438FB3](https://user-images.githubusercontent.com/90142558/222917655-f18fa1b0-b84e-43a7-8173-4cfa2fac066f.png)

**Comment by Deijin27** [comment]
I think I've fixed it in beta2, can you verify please?

**Comment by WhatAUsernameIHave** [comment]
Fixed!
