### ISSUE TITLE
Partial Transfer Plugin Section Update for 5.4

### ISSUE THREAD

**Issue by WhatAUsernameIHave** [Deijin27/RanseiLink#32]
Listed below are sections that need to be modified to reflect 5.4 properly:
(Note: I know the Plugin won't be updated until 5.4 is out of beta but I wanted to compile this list to make it easier when that time comes!)

**Missing:**
- ~~Max Link (Warrior)~~
- ~~Max Link (Pokemon)~~
- ~~Warrior Name Table~~
- Gimmick Range
- Banner

**Merge:**
- Scenario Pokemon
- Scenario Kingdoms
- Scenario Warriors

**Comment by Deijin27** [comment]
MaxLink (Warrior/Pokemon) are a different way of looking at the same data, and MaxLink is already an option.
WarriorNameTable: this is part of the BaseWarrior (it's the same file), it's by techicality that names even need to be referred to by id, since unlike pokemon evolutions which are in the same file as pokemon, the number of names is hard-coded.
Gimmick Range: will add
Banner: Will add

Merge those three: I think that makes sense yeah, they are intrinsically linked. Will do.

**Comment by Deijin27** [comment]
Also need to add scenario building

**Comment by Deijin27** [comment]
And similar stuff to changelist plugin

**Comment by Deijin27** [comment]
Done in beta-2
