### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by ForgottenIguana** [Deijin27/RanseiLink#4]
Hi, I'm trying to create a personalized mod and I changed a Pokemon's name and it gave me an error. Now I can't get back into the mod to change the name back and it's giving me this message when I try to open it.

https://user-images.githubusercontent.com/104934007/166803714-55306cc1-6785-4c15-afaa-90b40075e6d4.PNG

**Comment by Deijin27** [comment]
Pokemon's names aren't stored in the message files, it must be something else, perhaps something unique with the rom you used, perhaps due to a bug in the message parsing code that caused your message files to get corrupt.

It would be helpful if you could send over the mod that is giving you issues. Open ranseilink and right click on the mod in question, you should see an "Export mod" option. Then send the exported file here.

The other information in your mod should be safe, and I will help you recover the mod once we figure out the issue.

**Comment by ForgottenIguana** [comment]
Sure thing, thank you for the quick reply! Here's the file. Hopefully it's an easy fix!

[Pokemon Legends Rising v0.2.zip](https://github.com/Deijin27/RanseiLink/files/8626969/Pokemon.Legends.Rising.v0.2.zip)

**Comment by Deijin27** [comment]
Somehow the message block says there is 9 groups, and there is actually 7 plus two spaces for padding. Then it tries to read a message at offset 0 where a message is not, and thus explosions.

Here is a fixed version. 
[Pokemon Legends Rising - Fixed v0.2.zip](https://github.com/Deijin27/RanseiLink/files/8627179/Pokemon.Legends.Rising.-.Fixed.v0.2.zip)

Just to confirm it's not a problem with your rom, could you create a new mod based on the original unmodified rom you used to create your mod, and before opening it up or anything, right click and export it.

Also if you can remember, some questions:
- what version of ranseilink did you create the mod in originally?
- what version of ranseilink were you using when the mod broke?
- did you modify anything in the "Text" page?

**Comment by ForgottenIguana** [comment]
Looks like it's all fixed, thank you so much!

I created the mod in 4.3 and it also broke in 4.3. I did modify a few things in the "Text" page as well

**Comment by Deijin27** [comment]
You said you got an error when it was saving the mod. This lines up with my theory that it crashed during the process of saving the message block file, and this left a partially saved file which will not be loadable.

Saving the blocks to a different file first, then moving them across if successful should stop this from happening. You may lose your changes in one block, but everything else would be saved.

As for the actual cause of the original error, it would probably be hard to track down even if you had a screenshot of the original error. The most useful thing would be if you could remember what "Text" changes you made in the session where it crashed.

This is one of the downsides to saving these files in the format used in the game, it's hard to track down bugs because of the complexity. Weighing this against the benefit of being able to modify the code without breaking compatibility with existing mods is tough.

**Comment by ForgottenIguana** [comment]
So the only thing I remember from the initial error is that I changed one of the "Text" files from {pokemon:0}! {variable1:0}! to {Divinity}! {variable1:0}! It's a nickname from a game I played with friends.

I distinctly remember the error saying that wouldn't fly. (I'm fairly new to modding, so I'm sure I was missing something there.) This message was at the top of the error and I closed it because I thought I could fix it myself, but it had locked me out. Hope this helps at least a little!

**Comment by Deijin27** [comment]
That does help a lot. You need to be careful with changing the things in curly brackets {} because the are commands, in this case a parameter in the speech context. {pokemon:0} is replaced with the name of the current speech context pokemon. These curly bracket things are to make it easy to edit these in ranseilink; in the game files {pokemon:0} is actually some numeric code. Your {Divinity} is not a recognised command, therefore an error occurred.

I can add validation to the text boxes to make sure only valid commands are allowed. This should make it a lot safer for people when editing text.

**Comment by ForgottenIguana** [comment]
Sounds like a good idea. That is kinda what I figured the issue was, thanks for clearing that up!

**Comment by ForgottenIguana** [comment]
I actually had another question. I'm having an issue I'm not sure how to resolve. At the very start of the story, when Keiji is trying to teach you how to recruit warriors is when I'm having trouble.

Basically I try to go into the cave with the warrior to recruit and it tells me "This time, all Warriors must be selected in order to go into battle." I am selecting both the units I have and it still prompts me with this message. Not sure what I may have done to mess this up. Any ideas on how to fix this? Thanks!
